- name: Update apt cache
  apt: update_cache=yes

- name: Install developer packages
  apt: 
    name:
      - python-virtualenv
      - ninja-build
      - clang
      - clang-tidy
      - libftdi-dev
      - libftdi1-dev
      - gdb
      - gfortran
    state: present
