- name: Set up NodeSource signing key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Set up NodeSource repository for Node 10.x
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_10.x {{ ubuntu_release }} main"
    state: present

- name: Set up Yarn signing key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Set up Yarn repository
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
